### ISSUE TITLE
Questions about training

### ISSUE THREAD

**Issue by M15-3080** [meituan/YOLOv6#159]
During the training, I found that GPU was not fully utilized.  My batch-size: 64, workers: 16, device: 0
![XHIXFXW{W%`J`JLN}IY44`A](https://user-images.githubusercontent.com/91411583/176583036-a725659b-504b-4e38-b79c-baf8eaae8f9d.png)

**Comment by meituan-gengyifei** [comment]
Thanks for your attention! yolov6 does not completely occupy all graphics card resources during the training process, which is mainly due to the nature of pytorch. On the one hand, because the current model is in the size of n/s, the model is relatively small, and the memory usage is not large. On the other hand, batch=64 will not take up too much graphics card resources, but it is not recommended to increase the batch in order to improve resource utilization. The larger the batch, the better.

**Comment by mtjhl** [comment]
您的训练启动命令是？ @kkweil

**Comment by kkweil** [comment]
感谢回复！
这个问题我已经解决，是由于训练集的原因。



在 2022-08-19 10:43:58，"liangliang" ***@***.***> 写道：

您的训练启动命令是？ @kkweil
