### ISSUE TITLE
When to use DFL loss?

### ISSUE THREAD

**Issue by will1973** [meituan/YOLOv6#770]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [x] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

Hi, we noticed that the default config for n and s are not using dfl loss, are the results reported in V3.0 paper without self-distillation achieved by not enabling the DFL loss? In other words, should the DFL loss only be enabled when using self-distillation? Thank you!

**Comment by Chilicyy** [comment]
Hi, You can use dfl loss on small models anytime if you want better performance. In V3.0 paper, we use dfl loss for self-distillation, and drop dfl branch while inference for better performance-speed trade-off, because using extra dfl branch may slow the inference to a certain extend on small models. Hope it helps.

**Comment by will1973** [comment]
Got it, thanks!
